In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=(10, 4))

## 2d_arr[2d_idx] = 3d_arr

In [3]:
a

array([[0, 1, 4, 0],
       [3, 8, 2, 3],
       [2, 8, 9, 1],
       [8, 7, 2, 9],
       [0, 2, 6, 6],
       [4, 6, 3, 1],
       [5, 2, 6, 6],
       [6, 9, 1, 2],
       [8, 5, 5, 1],
       [1, 5, 0, 5]])

In [4]:
a[a]

array([[[0, 1, 4, 0],
        [3, 8, 2, 3],
        [0, 2, 6, 6],
        [0, 1, 4, 0]],

       [[8, 7, 2, 9],
        [8, 5, 5, 1],
        [2, 8, 9, 1],
        [8, 7, 2, 9]],

       [[2, 8, 9, 1],
        [8, 5, 5, 1],
        [1, 5, 0, 5],
        [3, 8, 2, 3]],

       [[8, 5, 5, 1],
        [6, 9, 1, 2],
        [2, 8, 9, 1],
        [1, 5, 0, 5]],

       [[0, 1, 4, 0],
        [2, 8, 9, 1],
        [5, 2, 6, 6],
        [5, 2, 6, 6]],

       [[0, 2, 6, 6],
        [5, 2, 6, 6],
        [8, 7, 2, 9],
        [3, 8, 2, 3]],

       [[4, 6, 3, 1],
        [2, 8, 9, 1],
        [5, 2, 6, 6],
        [5, 2, 6, 6]],

       [[5, 2, 6, 6],
        [1, 5, 0, 5],
        [3, 8, 2, 3],
        [2, 8, 9, 1]],

       [[8, 5, 5, 1],
        [4, 6, 3, 1],
        [4, 6, 3, 1],
        [3, 8, 2, 3]],

       [[3, 8, 2, 3],
        [4, 6, 3, 1],
        [0, 1, 4, 0],
        [4, 6, 3, 1]]])

In [20]:
a[a].shape

(10, 4, 4)

## 1d_arr[1d_idx] = 1d_arr

In [11]:
a[2]

array([2, 8, 9, 1])

In [12]:
a[2][np.array([0, 0, 3, 1])]

array([2, 2, 1, 8])

## 2d_arr[1d_idx] = 2d_arr

In [15]:
a[3]

array([8, 7, 2, 9])

In [14]:
a[a[3]]

array([[8, 5, 5, 1],
       [6, 9, 1, 2],
       [2, 8, 9, 1],
       [1, 5, 0, 5]])

## 1d_arr[2d_idx] = 2d_arr

In [15]:
a[3]

array([8, 7, 2, 9])

In [19]:
a[3][np.clip(a, a_min=0, a_max=3)]

array([[8, 7, 9, 8],
       [9, 9, 2, 9],
       [2, 9, 9, 7],
       [9, 9, 2, 9],
       [8, 2, 9, 9],
       [9, 9, 9, 7],
       [9, 2, 9, 9],
       [9, 9, 7, 2],
       [9, 9, 9, 7],
       [7, 9, 8, 9]])