In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [2]:
n = 1000
X = np.random.rand(n, 2)
x_m = X[:, 0] + np.random.normal(scale=0.05, size=n)
X = np.column_stack([X, x_m])

In [3]:
np.corrcoef(X, rowvar=False)

array([[1.00000000e+00, 6.20530934e-04, 9.85367633e-01],
       [6.20530934e-04, 1.00000000e+00, 2.80335518e-03],
       [9.85367633e-01, 2.80335518e-03, 1.00000000e+00]])

In [4]:
pca = PCA(n_components=2)

In [5]:
Xt = pca.fit_transform(X)

In [6]:
Xt.shape

(1000, 2)

In [7]:
pca.explained_variance_ratio_

array([0.66383311, 0.33127876])

In [8]:
pca.components_

array([[-6.97412535e-01, -2.46470774e-03, -7.16665669e-01],
       [-2.84610555e-03,  9.99995726e-01, -6.69471891e-04]])

In [9]:
np.corrcoef(Xt, rowvar=False)

array([[ 1.00000000e+00, -2.43475348e-17],
       [-2.43475348e-17,  1.00000000e+00]])